// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
pub type RegisterAccount = Registration;

#[rustfmt::skip]
pub type RotateCredential = Rotation;

#[rustfmt::skip]
pub type SetPolicy = Policy;

#[rustfmt::skip]
pub type PreparePlan = PlanPreparation;

#[rustfmt::skip]
pub type PrepareProjection = ProjectionPreparation;

#[rustfmt::skip]
pub type ApprovePlan = Approval;

#[rustfmt::skip]
pub type ApplyPlan = Application;

#[rustfmt::skip]
pub type RetireAccount = Retirement;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountRegistered {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CredentialRotated {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicySet {
    pub capability_policy_count: Integer,
    pub zone_policy_count: Integer,
}

#[rustfmt::skip]
pub type PlanPrepared = Plan;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanApproved(pub PlanIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanApplied(pub PlanIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountRetired {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestRejected {
    pub rejection_reason: RejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Registration {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub credential_handle: CredentialHandle,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rotation {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub credential_handle: CredentialHandle,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CapabilityDirective {
    Enable,
    Disable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CapabilityPolicy {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub capability: Capability,
    pub capability_directive: CapabilityDirective,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ZonePolicy {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub allowed_zones: Vec<DomainName>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Policy {
    pub zones: Vec<ZonePolicy>,
    pub capabilities: Vec<CapabilityPolicy>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanPreparation(pub DesiredState);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionPreparation {
    pub provider: Provider,
    pub projection: Projection,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Approval(pub PlanIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Application(pub PlanIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retirement {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    CredentialHandleUnknown,
    ProviderNotConfigured,
    AccountUnknown,
    PlanUnknown,
    PlanNotApproved,
    PlanGenerationFailed,
    CapabilityUnauthorized,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Plan {
    pub identifier: PlanIdentifier,
    pub provider: Provider,
    pub zone: DomainName,
    pub records_to_create: Vec<DomainNameSystemRecord>,
    pub records_to_update: Vec<DomainNameSystemRecord>,
    pub record_names_to_delete: Vec<DomainName>,
    pub redirects_to_create: Vec<RedirectRule>,
    pub redirects_to_update: Vec<RedirectRule>,
    pub redirect_sources_to_delete: Vec<DomainName>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DesiredState {
    pub provider: Provider,
    pub zone: DomainName,
    pub records: Vec<DomainNameSystemRecord>,
    pub redirects: Vec<RedirectRule>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Projection {
    pub projection_query: ProjectionQuery,
    pub records: Vec<DomainNameSystemRecord>,
    pub redirects: Vec<RedirectRule>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionQuery {
    pub domain: DomainName,
    pub projection_scope: ProjectionScope,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ProjectionScope {
    PublicRecords,
    AllRecords,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainNameSystemRecord {
    pub name: DomainName,
    pub record_kind: RecordKind,
    pub content: RecordContent,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectRule {
    pub source: DomainName,
    pub target: DomainName,
    pub redirect_status: RedirectStatus,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RecordKind {
    Address,
    AddressSix,
    CanonicalName,
    MailExchange,
    Text,
    Service,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RedirectStatus {
    Permanent,
    Temporary,
}

#[rustfmt::skip]
pub type RecordContent = String;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Provider {
    Cloudflare,
    GoogleCloud,
    Hetzner,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Capability {
    DomainNameSystemRecords,
    RedirectRules,
    CloudHosts,
    Networks,
    Firewalls,
    LoadBalancers,
}

#[rustfmt::skip]
pub type ProviderAccount = String;

#[rustfmt::skip]
pub type CredentialHandle = String;

#[rustfmt::skip]
pub type DomainName = String;

#[rustfmt::skip]
pub type PlanIdentifier = String;

#[rustfmt::skip]
pub type CommitSequence = Integer;

#[rustfmt::skip]
pub type StateDigest = Integer;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    RegisterAccount(RegisterAccount),
    RotateCredential(RotateCredential),
    SetPolicy(SetPolicy),
    PreparePlan(PreparePlan),
    PrepareProjection(PrepareProjection),
    ApprovePlan(ApprovePlan),
    ApplyPlan(ApplyPlan),
    RetireAccount(RetireAccount),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    AccountRegistered(AccountRegistered),
    CredentialRotated(CredentialRotated),
    PolicySet(PolicySet),
    PlanPrepared(PlanPrepared),
    PlanApproved(PlanApproved),
    PlanApplied(PlanApplied),
    AccountRetired(AccountRetired),
    RequestRejected(RequestRejected),
}

#[rustfmt::skip]
impl PlanApproved {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanIdentifier> for PlanApproved {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PlanApplied {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanIdentifier> for PlanApplied {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PlanPreparation {
    pub fn new(payload: DesiredState) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DesiredState {
        &self.0
    }
    pub fn into_payload(self) -> DesiredState {
        self.0
    }
}
#[rustfmt::skip]
impl From<DesiredState> for PlanPreparation {
    fn from(payload: DesiredState) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Approval {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanIdentifier> for Approval {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Application {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanIdentifier> for Application {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn register_account(payload: RegisterAccount) -> Self {
        Self::RegisterAccount(payload)
    }
    pub fn rotate_credential(payload: RotateCredential) -> Self {
        Self::RotateCredential(payload)
    }
    pub fn set_policy(payload: SetPolicy) -> Self {
        Self::SetPolicy(payload)
    }
    pub fn prepare_plan(payload: PreparePlan) -> Self {
        Self::PreparePlan(payload)
    }
    pub fn prepare_projection(payload: PrepareProjection) -> Self {
        Self::PrepareProjection(payload)
    }
    pub fn approve_plan(payload: ApprovePlan) -> Self {
        Self::ApprovePlan(payload)
    }
    pub fn apply_plan(payload: ApplyPlan) -> Self {
        Self::ApplyPlan(payload)
    }
    pub fn retire_account(payload: RetireAccount) -> Self {
        Self::RetireAccount(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn account_registered(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }
    pub fn credential_rotated(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }
    pub fn policy_set(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
    pub fn plan_prepared(payload: PlanPrepared) -> Self {
        Self::PlanPrepared(payload)
    }
    pub fn plan_approved(payload: PlanIdentifier) -> Self {
        Self::PlanApproved(PlanApproved::new(payload))
    }
    pub fn plan_applied(payload: PlanIdentifier) -> Self {
        Self::PlanApplied(PlanApplied::new(payload))
    }
    pub fn account_retired(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }
    pub fn request_rejected(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
impl From<AccountRegistered> for Output {
    fn from(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<CredentialRotated> for Output {
    fn from(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }
}

#[rustfmt::skip]
impl From<PolicySet> for Output {
    fn from(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
}

#[rustfmt::skip]
impl From<PlanApproved> for Output {
    fn from(payload: PlanApproved) -> Self {
        Self::PlanApproved(payload)
    }
}

#[rustfmt::skip]
impl From<PlanApplied> for Output {
    fn from(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
}

#[rustfmt::skip]
impl From<AccountRetired> for Output {
    fn from(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }
}

#[rustfmt::skip]
impl From<RequestRejected> for Output {
    fn from(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AccountRegistered {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CredentialRotated {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PolicySet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PlanApproved {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PlanApplied {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AccountRetired {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RequestRejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Registration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Rotation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CapabilityDirective {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CapabilityPolicy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ZonePolicy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Policy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PlanPreparation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ProjectionPreparation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Approval {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Application {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Retirement {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Plan {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DesiredState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Projection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ProjectionQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ProjectionScope {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DomainNameSystemRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RedirectRule {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RecordKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RedirectStatus {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Provider {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Capability {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DatabaseMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_REGISTER_ACCOUNT: u64 = 0x0000000000000000;
    pub const INPUT_ROTATE_CREDENTIAL: u64 = 0x0001000000000000;
    pub const INPUT_SET_POLICY: u64 = 0x0002000000000000;
    pub const INPUT_PREPARE_PLAN: u64 = 0x0003000000000000;
    pub const INPUT_PREPARE_PROJECTION: u64 = 0x0004000000000000;
    pub const INPUT_APPROVE_PLAN: u64 = 0x0005000000000000;
    pub const INPUT_APPLY_PLAN: u64 = 0x0006000000000000;
    pub const INPUT_RETIRE_ACCOUNT: u64 = 0x0007000000000000;
    pub const OUTPUT_ACCOUNT_REGISTERED: u64 = 0x0100000000000000;
    pub const OUTPUT_CREDENTIAL_ROTATED: u64 = 0x0101000000000000;
    pub const OUTPUT_POLICY_SET: u64 = 0x0102000000000000;
    pub const OUTPUT_PLAN_PREPARED: u64 = 0x0103000000000000;
    pub const OUTPUT_PLAN_APPROVED: u64 = 0x0104000000000000;
    pub const OUTPUT_PLAN_APPLIED: u64 = 0x0105000000000000;
    pub const OUTPUT_ACCOUNT_RETIRED: u64 = 0x0106000000000000;
    pub const OUTPUT_REQUEST_REJECTED: u64 = 0x0107000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    RegisterAccount,
    RotateCredential,
    SetPolicy,
    PreparePlan,
    PrepareProjection,
    ApprovePlan,
    ApplyPlan,
    RetireAccount,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    AccountRegistered,
    CredentialRotated,
    PolicySet,
    PlanPrepared,
    PlanApproved,
    PlanApplied,
    AccountRetired,
    RequestRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::RegisterAccount(_) => InputRoute::RegisterAccount,
            Self::RotateCredential(_) => InputRoute::RotateCredential,
            Self::SetPolicy(_) => InputRoute::SetPolicy,
            Self::PreparePlan(_) => InputRoute::PreparePlan,
            Self::PrepareProjection(_) => InputRoute::PrepareProjection,
            Self::ApprovePlan(_) => InputRoute::ApprovePlan,
            Self::ApplyPlan(_) => InputRoute::ApplyPlan,
            Self::RetireAccount(_) => InputRoute::RetireAccount,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::RegisterAccount(_) => short_header::INPUT_REGISTER_ACCOUNT,
            Self::RotateCredential(_) => short_header::INPUT_ROTATE_CREDENTIAL,
            Self::SetPolicy(_) => short_header::INPUT_SET_POLICY,
            Self::PreparePlan(_) => short_header::INPUT_PREPARE_PLAN,
            Self::PrepareProjection(_) => short_header::INPUT_PREPARE_PROJECTION,
            Self::ApprovePlan(_) => short_header::INPUT_APPROVE_PLAN,
            Self::ApplyPlan(_) => short_header::INPUT_APPLY_PLAN,
            Self::RetireAccount(_) => short_header::INPUT_RETIRE_ACCOUNT,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_REGISTER_ACCOUNT => Ok(InputRoute::RegisterAccount),
            short_header::INPUT_ROTATE_CREDENTIAL => Ok(InputRoute::RotateCredential),
            short_header::INPUT_SET_POLICY => Ok(InputRoute::SetPolicy),
            short_header::INPUT_PREPARE_PLAN => Ok(InputRoute::PreparePlan),
            short_header::INPUT_PREPARE_PROJECTION => Ok(InputRoute::PrepareProjection),
            short_header::INPUT_APPROVE_PLAN => Ok(InputRoute::ApprovePlan),
            short_header::INPUT_APPLY_PLAN => Ok(InputRoute::ApplyPlan),
            short_header::INPUT_RETIRE_ACCOUNT => Ok(InputRoute::RetireAccount),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::AccountRegistered(_) => OutputRoute::AccountRegistered,
            Self::CredentialRotated(_) => OutputRoute::CredentialRotated,
            Self::PolicySet(_) => OutputRoute::PolicySet,
            Self::PlanPrepared(_) => OutputRoute::PlanPrepared,
            Self::PlanApproved(_) => OutputRoute::PlanApproved,
            Self::PlanApplied(_) => OutputRoute::PlanApplied,
            Self::AccountRetired(_) => OutputRoute::AccountRetired,
            Self::RequestRejected(_) => OutputRoute::RequestRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::AccountRegistered(_) => short_header::OUTPUT_ACCOUNT_REGISTERED,
            Self::CredentialRotated(_) => short_header::OUTPUT_CREDENTIAL_ROTATED,
            Self::PolicySet(_) => short_header::OUTPUT_POLICY_SET,
            Self::PlanPrepared(_) => short_header::OUTPUT_PLAN_PREPARED,
            Self::PlanApproved(_) => short_header::OUTPUT_PLAN_APPROVED,
            Self::PlanApplied(_) => short_header::OUTPUT_PLAN_APPLIED,
            Self::AccountRetired(_) => short_header::OUTPUT_ACCOUNT_RETIRED,
            Self::RequestRejected(_) => short_header::OUTPUT_REQUEST_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_ACCOUNT_REGISTERED => Ok(OutputRoute::AccountRegistered),
            short_header::OUTPUT_CREDENTIAL_ROTATED => Ok(OutputRoute::CredentialRotated),
            short_header::OUTPUT_POLICY_SET => Ok(OutputRoute::PolicySet),
            short_header::OUTPUT_PLAN_PREPARED => Ok(OutputRoute::PlanPrepared),
            short_header::OUTPUT_PLAN_APPROVED => Ok(OutputRoute::PlanApproved),
            short_header::OUTPUT_PLAN_APPLIED => Ok(OutputRoute::PlanApplied),
            short_header::OUTPUT_ACCOUNT_RETIRED => Ok(OutputRoute::AccountRetired),
            short_header::OUTPUT_REQUEST_REJECTED => Ok(OutputRoute::RequestRejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}
