// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

pub type RegisterAccount = Registration;

pub type RotateCredential = Rotation;

pub type SetPolicy = Policy;

pub type PreparePlan = PlanPreparation;

pub type PrepareProjection = ProjectionPreparation;

pub type ApprovePlan = Approval;

pub type ApplyPlan = Application;

pub type RetireAccount = Retirement;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

pub type SignalArrived = Input;

pub type SemaWriteCompleted = SemaWriteOutput;

pub type SemaReadCompleted = SemaReadOutput;

pub type EffectCompleted = NexusEffectResult;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    ReplyToSignal(ReplyToSignal),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

pub type CommandSemaWrite = SemaWriteInput;

pub type CommandSemaRead = SemaReadInput;

pub type ReplyToSignal = Output;

pub type CommandEffect = NexusEffectCommand;

pub type Continue = NexusWork;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    CloudflareApplyPlan(CloudflareApplyPlan),
}

pub type CloudflareApplyPlan = ProviderApplyRequest;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    CloudflareApplied(CloudflareApplied),
}

pub type CloudflareApplied = ProviderApplyResult;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderApplyRequest {
    pub plan: Plan,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderApplyResult {
    pub plan_identifier: PlanIdentifier,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteInput {
    RegisterAccount(RegisterAccount),
    RotateCredential(RotateCredential),
    SetPolicy(SetPolicy),
    PreparePlan(PreparePlan),
    PrepareProjection(PrepareProjection),
    ApprovePlan(ApprovePlan),
    ApplyPlan(ApplyPlan),
    RetireAccount(RetireAccount),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadInput {
    ObservePlan(ObservePlan),
}

pub type ObservePlan = PlanIdentifier;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteOutput {
    AccountRegistered(AccountRegistered),
    CredentialRotated(CredentialRotated),
    PolicySet(PolicySet),
    PlanPrepared(PlanPrepared),
    PlanApproved(PlanApproved),
    PlanApplied(PlanApplied),
    AccountRetired(AccountRetired),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadOutput {
    PlanObserved(PlanObserved),
    Missed(Missed),
}

pub type PlanObserved = ObservedPlan;

pub type Missed = RejectionReport;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservedPlan {
    pub plan: Plan,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionReport {
    pub rejection_reason: RejectionReason,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Registration {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub credential_handle: CredentialHandle,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rotation {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub credential_handle: CredentialHandle,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CapabilityDirective {
    Enable,
    Disable,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CapabilityPolicy {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub capability: Capability,
    pub capability_directive: CapabilityDirective,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ZonePolicy {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub allowed_zones: Vec<DomainName>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Policy {
    pub zones: Vec<ZonePolicy>,
    pub capabilities: Vec<CapabilityPolicy>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanPreparation(pub DesiredState);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionPreparation {
    pub provider: Provider,
    pub projection: Projection,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Approval(pub PlanIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Application(pub PlanIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retirement {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountRegistered {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CredentialRotated {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicySet {
    pub capability_policy_count: Integer,
    pub zone_policy_count: Integer,
}

pub type PlanPrepared = Plan;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanApproved(pub PlanIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanApplied(pub PlanIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AccountRetired {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    CredentialHandleUnknown,
    ProviderNotConfigured,
    AccountUnknown,
    PlanUnknown,
    PlanNotApproved,
    PlanGenerationFailed,
    CapabilityUnauthorized,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestRejected {
    pub rejection_reason: RejectionReason,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Plan {
    pub identifier: PlanIdentifier,
    pub provider: Provider,
    pub zone: DomainName,
    pub records_to_create: Vec<DomainNameSystemRecord>,
    pub records_to_update: Vec<DomainNameSystemRecord>,
    pub record_names_to_delete: Vec<DomainName>,
    pub redirects_to_create: Vec<RedirectRule>,
    pub redirects_to_update: Vec<RedirectRule>,
    pub redirect_sources_to_delete: Vec<DomainName>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DesiredState {
    pub provider: Provider,
    pub zone: DomainName,
    pub records: Vec<DomainNameSystemRecord>,
    pub redirects: Vec<RedirectRule>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Projection {
    pub projection_query: ProjectionQuery,
    pub records: Vec<DomainNameSystemRecord>,
    pub redirects: Vec<RedirectRule>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionQuery {
    pub domain: DomainName,
    pub projection_scope: ProjectionScope,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ProjectionScope {
    PublicRecords,
    AllRecords,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainNameSystemRecord {
    pub name: DomainName,
    pub record_kind: RecordKind,
    pub content: RecordContent,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectRule {
    pub source: DomainName,
    pub target: DomainName,
    pub redirect_status: RedirectStatus,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RecordKind {
    Address,
    AddressSix,
    CanonicalName,
    MailExchange,
    Text,
    Service,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RedirectStatus {
    Permanent,
    Temporary,
}

pub type RecordContent = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Provider {
    Cloudflare,
    GoogleCloud,
    Hetzner,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Capability {
    DomainNameSystemRecords,
    RedirectRules,
    CloudHosts,
    Networks,
    Firewalls,
    LoadBalancers,
}

pub type ProviderAccount = String;

pub type CredentialHandle = String;

pub type DomainName = String;

pub type PlanIdentifier = String;

pub type CommitSequence = Integer;

pub type StateDigest = Integer;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    RegisterAccount(RegisterAccount),
    RotateCredential(RotateCredential),
    SetPolicy(SetPolicy),
    PreparePlan(PreparePlan),
    PrepareProjection(PrepareProjection),
    ApprovePlan(ApprovePlan),
    ApplyPlan(ApplyPlan),
    RetireAccount(RetireAccount),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    AccountRegistered(AccountRegistered),
    CredentialRotated(CredentialRotated),
    PolicySet(PolicySet),
    PlanPrepared(PlanPrepared),
    PlanApproved(PlanApproved),
    PlanApplied(PlanApplied),
    AccountRetired(AccountRetired),
    RequestRejected(RequestRejected),
}

impl PlanPreparation {
    pub fn new(payload: DesiredState) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &DesiredState {
        &self.0
    }

    pub fn into_payload(self) -> DesiredState {
        self.0
    }
}

impl From<DesiredState> for PlanPreparation {
    fn from(payload: DesiredState) -> Self {
        Self::new(payload)
    }
}

impl Approval {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }

    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}

impl From<PlanIdentifier> for Approval {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

impl Application {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }

    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}

impl From<PlanIdentifier> for Application {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

impl PlanApproved {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }

    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}

impl From<PlanIdentifier> for PlanApproved {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

impl PlanApplied {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }

    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}

impl From<PlanIdentifier> for PlanApplied {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

impl NexusWork {
    pub fn signal_arrived(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }

    pub fn sema_write_completed(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }

    pub fn sema_read_completed(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }

    pub fn effect_completed(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

impl NexusAction {
    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }

    pub fn command_sema_read(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }

    pub fn reply_to_signal(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }

    pub fn command_effect(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }

    pub fn r#continue(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

impl NexusEffectCommand {
    pub fn cloudflare_apply_plan(payload: CloudflareApplyPlan) -> Self {
        Self::CloudflareApplyPlan(payload)
    }
}

impl NexusEffectResult {
    pub fn cloudflare_applied(payload: CloudflareApplied) -> Self {
        Self::CloudflareApplied(payload)
    }
}

impl SemaWriteInput {
    pub fn register_account(payload: RegisterAccount) -> Self {
        Self::RegisterAccount(payload)
    }

    pub fn rotate_credential(payload: RotateCredential) -> Self {
        Self::RotateCredential(payload)
    }

    pub fn set_policy(payload: SetPolicy) -> Self {
        Self::SetPolicy(payload)
    }

    pub fn prepare_plan(payload: PreparePlan) -> Self {
        Self::PreparePlan(payload)
    }

    pub fn prepare_projection(payload: PrepareProjection) -> Self {
        Self::PrepareProjection(payload)
    }

    pub fn approve_plan(payload: ApprovePlan) -> Self {
        Self::ApprovePlan(payload)
    }

    pub fn apply_plan(payload: ApplyPlan) -> Self {
        Self::ApplyPlan(payload)
    }

    pub fn retire_account(payload: RetireAccount) -> Self {
        Self::RetireAccount(payload)
    }
}

impl SemaReadInput {
    pub fn observe_plan(payload: ObservePlan) -> Self {
        Self::ObservePlan(payload)
    }
}

impl SemaWriteOutput {
    pub fn account_registered(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }

    pub fn credential_rotated(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }

    pub fn policy_set(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }

    pub fn plan_prepared(payload: PlanPrepared) -> Self {
        Self::PlanPrepared(payload)
    }

    pub fn plan_approved(payload: PlanIdentifier) -> Self {
        Self::PlanApproved(PlanApproved::new(payload))
    }

    pub fn plan_applied(payload: PlanIdentifier) -> Self {
        Self::PlanApplied(PlanApplied::new(payload))
    }

    pub fn account_retired(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }
}

impl SemaReadOutput {
    pub fn plan_observed(payload: PlanObserved) -> Self {
        Self::PlanObserved(payload)
    }

    pub fn missed(payload: Missed) -> Self {
        Self::Missed(payload)
    }
}

impl Input {
    pub fn register_account(payload: RegisterAccount) -> Self {
        Self::RegisterAccount(payload)
    }

    pub fn rotate_credential(payload: RotateCredential) -> Self {
        Self::RotateCredential(payload)
    }

    pub fn set_policy(payload: SetPolicy) -> Self {
        Self::SetPolicy(payload)
    }

    pub fn prepare_plan(payload: PreparePlan) -> Self {
        Self::PreparePlan(payload)
    }

    pub fn prepare_projection(payload: PrepareProjection) -> Self {
        Self::PrepareProjection(payload)
    }

    pub fn approve_plan(payload: ApprovePlan) -> Self {
        Self::ApprovePlan(payload)
    }

    pub fn apply_plan(payload: ApplyPlan) -> Self {
        Self::ApplyPlan(payload)
    }

    pub fn retire_account(payload: RetireAccount) -> Self {
        Self::RetireAccount(payload)
    }
}

impl Output {
    pub fn account_registered(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }

    pub fn credential_rotated(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }

    pub fn policy_set(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }

    pub fn plan_prepared(payload: PlanPrepared) -> Self {
        Self::PlanPrepared(payload)
    }

    pub fn plan_approved(payload: PlanIdentifier) -> Self {
        Self::PlanApproved(PlanApproved::new(payload))
    }

    pub fn plan_applied(payload: PlanIdentifier) -> Self {
        Self::PlanApplied(PlanApplied::new(payload))
    }

    pub fn account_retired(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }

    pub fn request_rejected(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

impl From<AccountRegistered> for SemaWriteOutput {
    fn from(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }
}

impl From<CredentialRotated> for SemaWriteOutput {
    fn from(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }
}

impl From<PolicySet> for SemaWriteOutput {
    fn from(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
}

impl From<PlanApproved> for SemaWriteOutput {
    fn from(payload: PlanApproved) -> Self {
        Self::PlanApproved(payload)
    }
}

impl From<PlanApplied> for SemaWriteOutput {
    fn from(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
}

impl From<AccountRetired> for SemaWriteOutput {
    fn from(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }
}

impl From<AccountRegistered> for Output {
    fn from(payload: AccountRegistered) -> Self {
        Self::AccountRegistered(payload)
    }
}

impl From<CredentialRotated> for Output {
    fn from(payload: CredentialRotated) -> Self {
        Self::CredentialRotated(payload)
    }
}

impl From<PolicySet> for Output {
    fn from(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
}

impl From<PlanApproved> for Output {
    fn from(payload: PlanApproved) -> Self {
        Self::PlanApproved(payload)
    }
}

impl From<PlanApplied> for Output {
    fn from(payload: PlanApplied) -> Self {
        Self::PlanApplied(payload)
    }
}

impl From<AccountRetired> for Output {
    fn from(payload: AccountRetired) -> Self {
        Self::AccountRetired(payload)
    }
}

impl From<RequestRejected> for Output {
    fn from(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[cfg(feature = "nota-text")]
impl NexusWork {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusAction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusEffectCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusEffectResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProviderApplyRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProviderApplyResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaWriteInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaReadInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaWriteOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaReadOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ObservedPlan {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Registration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Rotation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CapabilityDirective {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CapabilityPolicy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ZonePolicy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Policy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PlanPreparation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionPreparation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Approval {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Application {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Retirement {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AccountRegistered {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CredentialRotated {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicySet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PlanApproved {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PlanApplied {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AccountRetired {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RequestRejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Plan {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DesiredState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Projection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionScope {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DomainNameSystemRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RedirectRule {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RecordKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RedirectStatus {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Provider {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Capability {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DatabaseMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_REGISTER_ACCOUNT: u64 = 0x0000000000000000;
    pub const INPUT_ROTATE_CREDENTIAL: u64 = 0x0001000000000000;
    pub const INPUT_SET_POLICY: u64 = 0x0002000000000000;
    pub const INPUT_PREPARE_PLAN: u64 = 0x0003000000000000;
    pub const INPUT_PREPARE_PROJECTION: u64 = 0x0004000000000000;
    pub const INPUT_APPROVE_PLAN: u64 = 0x0005000000000000;
    pub const INPUT_APPLY_PLAN: u64 = 0x0006000000000000;
    pub const INPUT_RETIRE_ACCOUNT: u64 = 0x0007000000000000;
    pub const OUTPUT_ACCOUNT_REGISTERED: u64 = 0x0100000000000000;
    pub const OUTPUT_CREDENTIAL_ROTATED: u64 = 0x0101000000000000;
    pub const OUTPUT_POLICY_SET: u64 = 0x0102000000000000;
    pub const OUTPUT_PLAN_PREPARED: u64 = 0x0103000000000000;
    pub const OUTPUT_PLAN_APPROVED: u64 = 0x0104000000000000;
    pub const OUTPUT_PLAN_APPLIED: u64 = 0x0105000000000000;
    pub const OUTPUT_ACCOUNT_RETIRED: u64 = 0x0106000000000000;
    pub const OUTPUT_REQUEST_REJECTED: u64 = 0x0107000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    RegisterAccount,
    RotateCredential,
    SetPolicy,
    PreparePlan,
    PrepareProjection,
    ApprovePlan,
    ApplyPlan,
    RetireAccount,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    AccountRegistered,
    CredentialRotated,
    PolicySet,
    PlanPrepared,
    PlanApproved,
    PlanApplied,
    AccountRetired,
    RequestRejected,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::RegisterAccount(_) => InputRoute::RegisterAccount,
            Self::RotateCredential(_) => InputRoute::RotateCredential,
            Self::SetPolicy(_) => InputRoute::SetPolicy,
            Self::PreparePlan(_) => InputRoute::PreparePlan,
            Self::PrepareProjection(_) => InputRoute::PrepareProjection,
            Self::ApprovePlan(_) => InputRoute::ApprovePlan,
            Self::ApplyPlan(_) => InputRoute::ApplyPlan,
            Self::RetireAccount(_) => InputRoute::RetireAccount,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::RegisterAccount(_) => short_header::INPUT_REGISTER_ACCOUNT,
            Self::RotateCredential(_) => short_header::INPUT_ROTATE_CREDENTIAL,
            Self::SetPolicy(_) => short_header::INPUT_SET_POLICY,
            Self::PreparePlan(_) => short_header::INPUT_PREPARE_PLAN,
            Self::PrepareProjection(_) => short_header::INPUT_PREPARE_PROJECTION,
            Self::ApprovePlan(_) => short_header::INPUT_APPROVE_PLAN,
            Self::ApplyPlan(_) => short_header::INPUT_APPLY_PLAN,
            Self::RetireAccount(_) => short_header::INPUT_RETIRE_ACCOUNT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_REGISTER_ACCOUNT => Ok(InputRoute::RegisterAccount),
            short_header::INPUT_ROTATE_CREDENTIAL => Ok(InputRoute::RotateCredential),
            short_header::INPUT_SET_POLICY => Ok(InputRoute::SetPolicy),
            short_header::INPUT_PREPARE_PLAN => Ok(InputRoute::PreparePlan),
            short_header::INPUT_PREPARE_PROJECTION => Ok(InputRoute::PrepareProjection),
            short_header::INPUT_APPROVE_PLAN => Ok(InputRoute::ApprovePlan),
            short_header::INPUT_APPLY_PLAN => Ok(InputRoute::ApplyPlan),
            short_header::INPUT_RETIRE_ACCOUNT => Ok(InputRoute::RetireAccount),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::AccountRegistered(_) => OutputRoute::AccountRegistered,
            Self::CredentialRotated(_) => OutputRoute::CredentialRotated,
            Self::PolicySet(_) => OutputRoute::PolicySet,
            Self::PlanPrepared(_) => OutputRoute::PlanPrepared,
            Self::PlanApproved(_) => OutputRoute::PlanApproved,
            Self::PlanApplied(_) => OutputRoute::PlanApplied,
            Self::AccountRetired(_) => OutputRoute::AccountRetired,
            Self::RequestRejected(_) => OutputRoute::RequestRejected,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::AccountRegistered(_) => short_header::OUTPUT_ACCOUNT_REGISTERED,
            Self::CredentialRotated(_) => short_header::OUTPUT_CREDENTIAL_ROTATED,
            Self::PolicySet(_) => short_header::OUTPUT_POLICY_SET,
            Self::PlanPrepared(_) => short_header::OUTPUT_PLAN_PREPARED,
            Self::PlanApproved(_) => short_header::OUTPUT_PLAN_APPROVED,
            Self::PlanApplied(_) => short_header::OUTPUT_PLAN_APPLIED,
            Self::AccountRetired(_) => short_header::OUTPUT_ACCOUNT_RETIRED,
            Self::RequestRejected(_) => short_header::OUTPUT_REQUEST_REJECTED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_ACCOUNT_REGISTERED => Ok(OutputRoute::AccountRegistered),
            short_header::OUTPUT_CREDENTIAL_ROTATED => Ok(OutputRoute::CredentialRotated),
            short_header::OUTPUT_POLICY_SET => Ok(OutputRoute::PolicySet),
            short_header::OUTPUT_PLAN_PREPARED => Ok(OutputRoute::PlanPrepared),
            short_header::OUTPUT_PLAN_APPROVED => Ok(OutputRoute::PlanApproved),
            short_header::OUTPUT_PLAN_APPLIED => Ok(OutputRoute::PlanApplied),
            short_header::OUTPUT_ACCOUNT_RETIRED => Ok(OutputRoute::AccountRetired),
            short_header::OUTPUT_REQUEST_REJECTED => Ok(OutputRoute::RequestRejected),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
    EffectCompleted,
}

impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusActionRoute {
    CommandSemaWrite,
    CommandSemaRead,
    ReplyToSignal,
    CommandEffect,
    Continue,
}

impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaWriteInputRoute {
    RegisterAccount,
    RotateCredential,
    SetPolicy,
    PreparePlan,
    PrepareProjection,
    ApprovePlan,
    ApplyPlan,
    RetireAccount,
}

impl SemaWriteInput {
    pub fn route(&self) -> SemaWriteInputRoute {
        match self {
            Self::RegisterAccount(_) => SemaWriteInputRoute::RegisterAccount,
            Self::RotateCredential(_) => SemaWriteInputRoute::RotateCredential,
            Self::SetPolicy(_) => SemaWriteInputRoute::SetPolicy,
            Self::PreparePlan(_) => SemaWriteInputRoute::PreparePlan,
            Self::PrepareProjection(_) => SemaWriteInputRoute::PrepareProjection,
            Self::ApprovePlan(_) => SemaWriteInputRoute::ApprovePlan,
            Self::ApplyPlan(_) => SemaWriteInputRoute::ApplyPlan,
            Self::RetireAccount(_) => SemaWriteInputRoute::RetireAccount,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaReadInputRoute {
    ObservePlan,
}

impl SemaReadInput {
    pub fn route(&self) -> SemaReadInputRoute {
        match self {
            Self::ObservePlan(_) => SemaReadInputRoute::ObservePlan,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaWriteOutputRoute {
    AccountRegistered,
    CredentialRotated,
    PolicySet,
    PlanPrepared,
    PlanApproved,
    PlanApplied,
    AccountRetired,
}

impl SemaWriteOutput {
    pub fn route(&self) -> SemaWriteOutputRoute {
        match self {
            Self::AccountRegistered(_) => SemaWriteOutputRoute::AccountRegistered,
            Self::CredentialRotated(_) => SemaWriteOutputRoute::CredentialRotated,
            Self::PolicySet(_) => SemaWriteOutputRoute::PolicySet,
            Self::PlanPrepared(_) => SemaWriteOutputRoute::PlanPrepared,
            Self::PlanApproved(_) => SemaWriteOutputRoute::PlanApproved,
            Self::PlanApplied(_) => SemaWriteOutputRoute::PlanApplied,
            Self::AccountRetired(_) => SemaWriteOutputRoute::AccountRetired,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaReadOutputRoute {
    PlanObserved,
    Missed,
}

impl SemaReadOutput {
    pub fn route(&self) -> SemaReadOutputRoute {
        match self {
            Self::PlanObserved(_) => SemaReadOutputRoute::PlanObserved,
            Self::Missed(_) => SemaReadOutputRoute::Missed,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SignalObjectName {
    Input(InputRoute),
    Output(OutputRoute),
    Started,
    Stopped,
    Admitted,
    Rejected,
    Triaged,
    Replied,
}

impl SignalObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Input(route) => match route {
                InputRoute::RegisterAccount => "SignalInputRegisterAccount",
                InputRoute::RotateCredential => "SignalInputRotateCredential",
                InputRoute::SetPolicy => "SignalInputSetPolicy",
                InputRoute::PreparePlan => "SignalInputPreparePlan",
                InputRoute::PrepareProjection => "SignalInputPrepareProjection",
                InputRoute::ApprovePlan => "SignalInputApprovePlan",
                InputRoute::ApplyPlan => "SignalInputApplyPlan",
                InputRoute::RetireAccount => "SignalInputRetireAccount",
            },
            Self::Output(route) => match route {
                OutputRoute::AccountRegistered => "SignalOutputAccountRegistered",
                OutputRoute::CredentialRotated => "SignalOutputCredentialRotated",
                OutputRoute::PolicySet => "SignalOutputPolicySet",
                OutputRoute::PlanPrepared => "SignalOutputPlanPrepared",
                OutputRoute::PlanApproved => "SignalOutputPlanApproved",
                OutputRoute::PlanApplied => "SignalOutputPlanApplied",
                OutputRoute::AccountRetired => "SignalOutputAccountRetired",
                OutputRoute::RequestRejected => "SignalOutputRequestRejected",
            },
            Self::Started => "SignalStarted",
            Self::Stopped => "SignalStopped",
            Self::Admitted => "SignalAdmitted",
            Self::Rejected => "SignalRejected",
            Self::Triaged => "SignalTriaged",
            Self::Replied => "SignalReplied",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}

impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => match route {
                NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
            },
            Self::Action(route) => match route {
                NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                NexusActionRoute::Continue => "NexusActionContinue",
            },
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaObjectName {
    WriteInput(SemaWriteInputRoute),
    ReadInput(SemaReadInputRoute),
    WriteOutput(SemaWriteOutputRoute),
    ReadOutput(SemaReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}

impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => match route {
                SemaWriteInputRoute::RegisterAccount => "SemaWriteInputRegisterAccount",
                SemaWriteInputRoute::RotateCredential => "SemaWriteInputRotateCredential",
                SemaWriteInputRoute::SetPolicy => "SemaWriteInputSetPolicy",
                SemaWriteInputRoute::PreparePlan => "SemaWriteInputPreparePlan",
                SemaWriteInputRoute::PrepareProjection => "SemaWriteInputPrepareProjection",
                SemaWriteInputRoute::ApprovePlan => "SemaWriteInputApprovePlan",
                SemaWriteInputRoute::ApplyPlan => "SemaWriteInputApplyPlan",
                SemaWriteInputRoute::RetireAccount => "SemaWriteInputRetireAccount",
            },
            Self::ReadInput(route) => match route {
                SemaReadInputRoute::ObservePlan => "SemaReadInputObservePlan",
            },
            Self::WriteOutput(route) => match route {
                SemaWriteOutputRoute::AccountRegistered => "SemaWriteOutputAccountRegistered",
                SemaWriteOutputRoute::CredentialRotated => "SemaWriteOutputCredentialRotated",
                SemaWriteOutputRoute::PolicySet => "SemaWriteOutputPolicySet",
                SemaWriteOutputRoute::PlanPrepared => "SemaWriteOutputPlanPrepared",
                SemaWriteOutputRoute::PlanApproved => "SemaWriteOutputPlanApproved",
                SemaWriteOutputRoute::PlanApplied => "SemaWriteOutputPlanApplied",
                SemaWriteOutputRoute::AccountRetired => "SemaWriteOutputAccountRetired",
            },
            Self::ReadOutput(route) => match route {
                SemaReadOutputRoute::PlanObserved => "SemaReadOutputPlanObserved",
                SemaReadOutputRoute::Missed => "SemaReadOutputMissed",
            },
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectName {
    Signal(SignalObjectName),
    Nexus(NexusObjectName),
    Sema(SemaObjectName),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct TraceEvent(pub ObjectName);

impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Signal(object_name) => object_name.name(),
            Self::Nexus(object_name) => object_name.name(),
            Self::Sema(object_name) => object_name.name(),
        }
    }
}

impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }

    pub fn object_name(&self) -> ObjectName {
        self.0
    }

    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct MessageIdentifier(pub Integer);
#[cfg(feature = "nota-text")]
impl MessageIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum MessageRoot {
    Input,
    Output,
}

pub mod schema {
    #[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
    pub enum Plane<SignalRoot, NexusRoot, SemaRoot> {
        Signal(super::Signal<SignalRoot>),
        Nexus(super::Nexus<NexusRoot>),
        Sema(super::Sema<SemaRoot>),
    }

    impl<SignalRoot, NexusRoot, SemaRoot> Plane<SignalRoot, NexusRoot, SemaRoot> {
        pub fn origin_route(&self) -> super::OriginRoute {
            match self {
                Self::Signal(message) => message.origin_route(),
                Self::Nexus(message) => message.origin_route(),
                Self::Sema(message) => message.origin_route(),
            }
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}

pub trait MessageSentHook {
    type Error;

    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}

pub trait MessageProcessedHook<Reply> {
    type Error;

    fn message_processed(&mut self, event: MessageProcessed<Reply>) -> Result<(), Self::Error>;
}

impl MessageSent {
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}

impl<Reply> MessageProcessed<Reply> {
    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, reply: Reply) -> Self {
        Self { identifier, origin_route, reply }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn into_reply(self) -> Reply {
        self.reply
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}

impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Input> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Input,
            short_header: self.root().short_header(),
        }
    }
}

impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Output> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Output,
            short_header: self.root().short_header(),
        }
    }
}

pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

pub mod sema {
    pub type WriteInput = super::SemaWriteInput;
    pub type WriteOutput = super::SemaWriteOutput;
    pub type ReadInput = super::SemaReadInput;
    pub type ReadOutput = super::SemaReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl SemaWriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaWriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}

impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => write!(formatter, "actor resource busy: {message}"),
            Self::ConfigurationInvalid(message) => write!(formatter, "actor configuration invalid: {message}"),
        }
    }
}

impl std::error::Error for ActorStartFailure {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}

impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => write!(formatter, "actor resource locked: {message}"),
            Self::ChildStillRunning(message) => write!(formatter, "actor child still running: {message}"),
        }
    }
}

impl std::error::Error for ActorStopFailure {}

pub trait SignalEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_signal_activation(&self, _object_name: SignalObjectName) {}
    fn trace_signal_admitted(&self) {
        self.trace_signal_activation(SignalObjectName::Admitted);
    }
    fn trace_signal_rejected(&self) {
        self.trace_signal_activation(SignalObjectName::Rejected);
    }
    fn trace_signal_triaged(&self) {
        self.trace_signal_activation(SignalObjectName::Triaged);
    }
    fn trace_signal_replied(&self) {
        self.trace_signal_activation(SignalObjectName::Replied);
    }

    fn triage_inner(&self, input: signal::Signal<signal::Input>) -> nexus::Nexus<nexus::Work>;
    fn reply_inner(&self, output: nexus::Nexus<nexus::Action>) -> signal::Signal<signal::Output>;

    fn triage(&self, input: signal::Signal<signal::Input>) -> nexus::Nexus<nexus::Work> {
        let output = self.triage_inner(input);
        self.trace_signal_triaged();
        output
    }

    fn reply(&self, output: nexus::Nexus<nexus::Action>) -> signal::Signal<signal::Output> {
        let signal_output = self.reply_inner(output);
        self.trace_signal_replied();
        signal_output
    }
}

pub trait NexusEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }

    fn decide(&mut self, input: nexus::Nexus<nexus::Work>) -> nexus::Nexus<nexus::Action>;

    fn execute(&mut self, input: nexus::Nexus<nexus::Work>) -> nexus::Nexus<nexus::Action> {
        self.trace_nexus_entered();
        let output = self.decide(input);
        self.trace_nexus_decided();
        output
    }
}

pub trait SemaEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }

    fn apply_inner(&mut self, input: sema::Sema<sema::WriteInput>) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(&self, input: sema::Sema<sema::ReadInput>) -> sema::Sema<sema::ReadOutput>;

    fn apply(&mut self, input: sema::Sema<sema::WriteInput>) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }

    fn observe(&self, input: sema::Sema<sema::ReadInput>) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
